notifications:
 email:
  recipients:
   - pierrick.rogermele@icloud.com

before_install:
    - export GALAXY_RELEASE=release_17.01
    - export PLANEMO_RELEASE=0.42.1
      
install:
    - pip install planemo==$PLANEMO_RELEASE
       
script:
    - planemo lint .
    - planemo test --conda_auto_init --conda_auto_install --conda_dependency_resolution --galaxy_branch $GALAXY_RELEASE --no_cache_galaxy .
